imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: app.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: "%app_version%"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'LCSAppBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [LCSAppBundle]
    #java: /usr/bin/java
#    node: "C:\\Program Files (x86)\\nodejs\\node.exe"
#    filters:
#        uglifyjs2:
#            bin: "C:\\Program Files\\Aimara\\wamp\\www\\lcs\\UglifyJS2\\bin\\uglifyjs"
#        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        base_scripts:
            inputs:
                - '@LCSAppBundle/Resources/public/js/jquery-2.1.4.min.js'
                - '@LCSAppBundle/Resources/public/bootstrap/js/bootstrap.min.js'
                - '@LCSAppBundle/Resources/public/js/jquery.form.js'
                - '@LCSAppBundle/Resources/public/js/lcs.namespace.js'
                - '@LCSAppBundle/Resources/public/js/lcs.ui.js'
                - '@LCSAppBundle/Resources/public/js/lcs.navigation.js'
                - '@LCSAppBundle/Resources/public/jquery.validation/jquery.validate.min.js'
                - '@LCSAppBundle/Resources/public/jquery.validation/localization/messages_es_AR.min.js'
                - '@LCSAppBundle/Resources/public/js/lcs.validation.extension.js'
                - '@LCSAppBundle/Resources/public/moment/moment-with-locales.min.js'
                - '@LCSAppBundle/Resources/public/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js'


## Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryptation%"
    spool:
        type: file
        path: '%kernel.root_dir%/spool'

guzzle:
    clients:
        ws_crm_rest:
            base_url: "%lcs_app.ws_crm_rest.base_url%"

            # custom headers
            headers:
                Accept: "application/json"

            # guzzle client options (full description here: http://guzzle.readthedocs.org/en/latest/request-options.html)
            # NOTE: "headers" option is not accepted here as it is provided as described above.
            options:
                auth:
                    - acme     # login
                    - pa55w0rd # password
                timeout: 30

            # plugin settings
            plugin:
                wsse:
                    username:   "acme"
                    password:   "pa55w0rd"
                    #created_at: "-10 seconds" # optional
